version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vblPzWkQnzyGmEZBDOKWnejzFAVjGYTJ
      POSTGRES_DB: evolution_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: evolution_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
